import React from 'react'
import { Document, Page, Text, View } from '@react-pdf/renderer'
import { format } from 'date-fns'
import { pdfStyles } from './styles'

interface DailyBoardCase {
  id: string
  caseNumber: string | null
  firstParty: string | null
  oppositeParty: string | null
  courtName: string | null
  courtNo: string | null
  fixedFor: string | null
  judgeName: string | null
  caseType: string | null
}

interface DailyBoardProps {
  date: Date
  cases: DailyBoardCase[]
  profile: {
    fullName: string | null
    officeName: string | null
    mobile: string | null
    logoUrl: string | null
  }
  groupBy?: 'court' | 'judge'
}

function truncateStr(str: string, n: number): string {
  return str.length > n ? str.substring(0, n - 1) + '...' : str
}

export function DailyBoardPDF({ date, cases, profile, groupBy = 'court' }: DailyBoardProps) {
  const grouped = cases.reduce((acc, c) => {
    const key =
      groupBy === 'court'
        ? c.courtName ?? 'Unknown Court'
        : c.judgeName ?? 'Unknown Judge'
    if (!acc[key]) acc[key] = []
    acc[key].push(c)
    return acc
  }, {} as Record<string, DailyBoardCase[]>)

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <View>
            <Text style={pdfStyles.officeName}>
              {profile.officeName ?? profile.fullName ?? 'Advocate'}
            </Text>
            {profile.mobile && (
              <Text style={{ fontSize: 9, color: '#64748B', marginTop: 2 }}>
                {profile.mobile}
              </Text>
            )}
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={{ fontSize: 14, fontFamily: 'Helvetica-Bold', color: '#4F46E5' }}>
              Daily Board
            </Text>
            <Text style={{ fontSize: 11, color: '#334155', marginTop: 2 }}>
              {format(date, 'EEEE, dd MMMM yyyy')}
            </Text>
            <Text style={{ fontSize: 9, color: '#94A3B8', marginTop: 1 }}>
              {cases.length} {cases.length === 1 ? 'case' : 'cases'}
            </Text>
          </View>
        </View>

        {/* Cases grouped by court/judge */}
        {Object.entries(grouped).map(([groupName, groupCases]) => (
          <View key={groupName} style={{ marginBottom: 16 }} wrap={false}>
            <Text style={pdfStyles.sectionTitle}>{groupName}</Text>

            <View style={pdfStyles.table}>
              <View style={pdfStyles.tableHeader}>
                <Text style={[pdfStyles.tableHeaderCell, { width: '8%' }]}>S.No</Text>
                <Text style={[pdfStyles.tableHeaderCell, { width: '22%' }]}>Case No.</Text>
                <Text style={[pdfStyles.tableHeaderCell, { width: '35%' }]}>Parties</Text>
                <Text style={[pdfStyles.tableHeaderCell, { width: '20%' }]}>Fixed For</Text>
                <Text style={[pdfStyles.tableHeaderCell, { width: '15%' }]}>Type</Text>
              </View>

              {groupCases.map((c, i) => (
                <View
                  key={c.id}
                  style={[pdfStyles.tableRow, i % 2 !== 0 ? { backgroundColor: '#FAFAFA' } : {}]}
                >
                  <Text style={[pdfStyles.tableCell, { width: '8%' }]}>{i + 1}</Text>
                  <Text style={[pdfStyles.tableCell, { width: '22%', fontFamily: 'Courier', fontSize: 8 }]}>
                    {c.caseNumber ?? '—'}
                  </Text>
                  <View style={{ width: '35%' }}>
                    <Text style={[pdfStyles.tableCell, { fontFamily: 'Helvetica-Bold', fontSize: 8 }]}>
                      {truncateStr(c.firstParty ?? '—', 35)}
                    </Text>
                    <Text style={[pdfStyles.tableCell, { color: '#94A3B8', fontSize: 8 }]}>
                      vs {truncateStr(c.oppositeParty ?? '—', 35)}
                    </Text>
                  </View>
                  <Text style={[pdfStyles.tableCell, { width: '20%', color: '#4F46E5', fontSize: 8 }]}>
                    {c.fixedFor ?? '—'}
                  </Text>
                  <Text style={[pdfStyles.tableCell, { width: '15%', fontSize: 8 }]}>
                    {c.caseType ?? '—'}
                  </Text>
                </View>
              ))}
            </View>
          </View>
        ))}

        {cases.length === 0 && (
          <Text style={{ textAlign: 'center', color: '#94A3B8', marginTop: 40 }}>
            No cases scheduled for this date.
          </Text>
        )}

        {/* Footer */}
        <View style={pdfStyles.footer} fixed>
          <Text>Generated by Advocase • {format(new Date(), 'dd MMM yyyy HH:mm')}</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}
